# Generated by Django 4.1.2 on 2022-10-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoutilitare', '0001_initial'),
        ('client', '0002_client_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoutilitare.autoutilitare'),
        ),
    ]
