# Generated by Django 4.1.2 on 2022-10-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='start_date',
        ),
    ]
